### ISSUE TITLE
Need a better Chess board with co-ordinates

### ISSUE THREAD

**Issue by gopsbits** [chesspecker/chesspecker#47]
### Describe the feature you'd like to request

Currently, do not see the co-ordinates of the chess board. Need to have a better chessboard.
Please keep options for users to select the board and pieces from usability point of view.

**Comment by pnxdxt** [comment]
Hi @gopsbits 
Thanks for the feature request!

The chessboard is currently being re-written, you can have a preview at : https://beta.chesspecker.com/play/622c50e882560a559562cc12
