### ISSUE TITLE
Make it easier to contribute (dockerfile ?)

### ISSUE THREAD

**Issue by Nicolas-Menettrier** [chesspecker/chesspecker#51]
### Describe the feature you'd like to request

I would like to contribute on my free time but there is no easy step to be able to build the project in a working state (I can launch it but it will crash as soon as I try to connect because env variable are missing). A dockerfile would be a cool nice to have for this project (create mongoose and project in one command). There is also no documentation about the env variable required to launch the project so it's a bit disturbing when you try to launch it for the first time. (I want to fix the arrow on the board that disappear after a new render I guess).

I can do the dockerfile but I'll need the default env variable to try everything

**Comment by pnxdxt** [comment]
Sure.
Quick todo list:
- implement docker and running a local mongodb instance
- handle environment variables to avoid leaks and maybe get a test Lichess token
- the callback function from Lichess should send to localhost 

docs on docker / yarn implementation with caching mechanism
// https://hackernoon.com/using-yarn-with-docker-c116ad289d56

**Comment by pnxdxt** [comment]
Hi @Nicolas-Menettrier 

Sorry for the long wait!

I added a few files to help you running the project locally.
Checkout the readme, it should be straightforward.

Let me know if you have any issue!

**Comment by Nicolas-Menettrier** [comment]
I'll give you feedback at midday, thanks for this feature! I'll join the discord tonight, can't wait to contribute 😃
