### ISSUE TITLE
Failing restoring with mongorestore dump

### ISSUE THREAD

**Issue by VasileiosNt** [chesspecker/chesspecker#56]
### Describe the Bug

Running `mongorestore dump` inside the docker image returns : 
```
Failed: chesspecker.puzzles: error restoring from dump/chesspecker/puzzles.bson: reading bson input: invalid BSONSize: 1936876918 bytes
```

### Expected Behavior

Restore the db.

### To Reproduce

Follow Readme installation guide.

### What browser are you using? (if relevant)

Mozzila (latest)

**Comment by pnxdxt** [comment]
This should now be fixed by commit cb39dd0bfdd81249fae5279bab373015ad47969e

Please make sure you have [Git LFS](https://git-lfs.github.com) installed.

I update the README, but you might need to re-clone the repo.
