### ISSUE TITLE
Easy fix - typo in Spaced Repetition Pop Up

### ISSUE THREAD

**Issue by zeezop** [chesspecker/chesspecker#60]
### Describe the Bug

![image](https://user-images.githubusercontent.com/42500749/173253771-c2686ea3-6eb2-47b8-8b3a-f05f2cfd7b86.png)

### Expected Behavior

Small spelling error "Desactivate" should be "Deactivate"

### To Reproduce

Turning "Spaced Repetition" off

**Comment by zeezop** [comment]
Also spelling of "LOOSE" should be "LOSE"

**Comment by pnxdxt** [comment]
@zeezop thanks & sorry. Fixed!
